### ISSUE TITLE
loop when rendering text

### ISSUE THREAD

**Issue by byorgey** [diagrams/diagrams-cairo#59]
The cairo backend yields &lt;&lt;loop&gt;&gt; when I try to run the following program:

```
{-# LANGUAGE NoMonomorphismRestriction #-}

import Diagrams.Prelude
import Diagrams.Backend.Cairo.CmdLine

import Control.Arrow
import Data.List

import Diagrams.TwoD.Layout.Tree hiding (leaf)
import Data.Tree

cunit :: String -> Tree String
cunit x = Node (x ++ ".o") [ Node (x ++ ".c") [] ]

t :: Tree String
t = Node "prog.exe"
    [ cunit "foo"
    , cunit "bar"
    , cunit "baz"
    ]

dia :: Diagram B
dia = lw thin
    . frame 0.5
    . renderTree (\t -> text t # fc (pickColor t) # fontSizeL 0.8 <> roundedRect 6 2 0.5 # fc white) (~~)
    . (fmap . second) reflectY
    . symmLayout' (with & slWidth  .~ const (-3,3)
                        & slHeight .~ const (-1,1)
                        & slHSep   .~ 2
                        & slVSep   .~ 2
                  )
    $ t    -- $

pickColor t
  | "c" `isSuffixOf` t = blue
  | "o" `isSuffixOf` t = green
  | otherwise          = red

main = defaultMain dia
```

When I am not working frantically on a talk I will try to come up with a stripped-down version.  This example renders fine with the SVG backend.

**Comment by byorgey** [comment]
The culprit seems to be text.  The following code causes `<<loop>>` to be printed:

```
import Diagrams.Prelude
import Diagrams.Backend.Cairo.CmdLine

main = defaultMain (text "abc" <> square 1)
```
It still gives `<<loop>>` even with the `square 1` taken away as well.

**Comment by byorgey** [comment]
Well, that was easy to find:

```
let tr = tr <> reflectionY
```

oops. See here: https://github.com/diagrams/diagrams-cairo/blob/master/src/Diagrams/Backend/Cairo/Internal.hs#L402

Simple fix coming shortly.

**Comment by bergey** [comment]
[sigh]  We need regression tests.  I need to look at how the new Measure works; I don't understand the Text instance post-https://github.com/diagrams/diagrams-cairo/commit/64ec0c44c628c5ac13b7d521f949a5503bbe56cc

**Comment by cchalmers** [comment]
Looks like this happened because of a mixup in merging. I didn't test it because I don't have Cairo installed so and diagrams/diagrams-cairo#57 ended up getting merged without getting checked.

As for the changes for the new measure, basically the `tt` in `Text` only captures the non-scaling transform (so the `(avgScale tt *)` bit in my commit is actually redundant). All scaling is recorded in the `FontSizeM` attribute. Looking back I should have written a bit more explaining it.

I also had to include a `Recommend` in the font size because the default size is `local`. Otherwise if the user doesn't specify a font size, none of the scaling gets recorded. Another consequence is any local scaling before committing a font size is ignored. But this is consistent with how other measured attributes work.

**Comment by bergey** [comment]
Your explanation is very helpful.  Thank you.
