### ISSUE TITLE
Please accept ownership of diagrams-gi-cairo

### ISSUE THREAD

**Issue by AshleyYakeley** [diagrams/diagrams-cairo#76]
I've created [diagrams-gi-cairo](/AshleyYakeley/diagrams-gi-cairo), a fork of the diagrams-cairo repository to work with haskell-gi instead of gtk2hs. As you might expect, the actual code changes are quite minor, mostly it's wrangling packages and modules.

It seems to work with the one diagram I tried.

Please accept ownership of the project. Think of this as a PR for the addition of an entire repository.

* Copy the repository into the diagrams team
* Review the changes I've made
* Adjust the documentation, etc.
* Probably, put back the version bounds in the .cabal file
* Make a release to Hackage

**Comment by byorgey** [comment]
Thanks!  Hope to take a look soon.

**Comment by byorgey** [comment]
I've forked diagrams-gi-cairo into the diagrams organization.  It might take me a bit longer to get a chance to look through it, make any adjustments, and release it.  (Though it doesn't have to be me.)

**Comment by YellowOnion** [comment]
Pretty sure the  `cairo` package is somewhat dead as it only supports the gtk3 only gtk2hs project, and with everything moving to gtk4, the only way get diagrams working, and future proof is to use the `gi-cairo` package.

Can you look at getting this fixed up and merged? I want to try `diagrams` in my gtk4 app, but this is a blocker.

**Comment by leftaroundabout** [comment]
@YellowOnion well, you can already use [`diagrams-gi-cairo`](https://hackage.haskell.org/package/diagrams-gi-cairo)... what exactly are you requesting here?

There _is_ a point to be made that `diagrams-cairo` should not be the recommended backend anymore, and that the documentation ought to defer to `diagrams-gi-cairo` instead.

Also, last time I tried the GI version (about a year ago) there were problems in particular for text. Haven't gotten around to looking closer into that (not sure if it's actually the fault of gi-cairo or I was just doing something nonstandard that just happened to work in `diagrams-cairo`). Quite possible there are some things to be fixed in `diagrams-gi-cairo`, but then you should open concrete issues for those.

**Comment by YellowOnion** [comment]
> @YellowOnion well, you can already use [`diagrams-gi-cairo`](https://hackage.haskell.org/package/diagrams-gi-cairo)... what exactly are you requesting here?

Oh sorry, I see no references to this sub project in the main documentation, and somehow missed that it's on hackage, saw this thread, so I assumed the sub project was abandoned based on this open bug report...I guess I was getting tired.

I'll have test of that, Still brain storming ways to get variable width strokes (trying to do some calligraphic rendering from a graphics tablet).

**Comment by AshleyYakeley** [comment]
Can this issue be closed, if the diagrams group has taken ownership?

**Comment by byorgey** [comment]
Yes, I think I just forgot to close this issue.  And good point about updating documentation to refer to `diagrams-gi-cairo` instead of `diagrams-cairo`, I will keep that in mind as I update things going forward.
