### ISSUE TITLE
The base dependency version on the Hackage is inconsistent with the actual version in tar.gz

### ISSUE THREAD

**Issue by chansey97** [diagrams/diagrams-cairo#83]
At the moment, the base dependency version of diagrams-cairo from https://hackage.haskell.org/package/ shows:

> base (>=4.2 && <4.20), 

However, after downloading the actual file from https://hackage.haskell.org/package/diagrams-cairo-1.4.2.1/diagrams-cairo-1.4.2.1.tar.gz and extract the `diagrams-cairo.cabal`, it shows

> Build-depends:       base >= 4.2 && < 4.19,

This causes diagrams-cairo to fail to compile on the latest ghc-9.8.1 version.

**Comment by byorgey** [comment]
Hi @chansey97 , thanks for the report!  However, this is expected: when you download the tarball directly using the URL you cited, you get the original version of the package upload.  But there have been a couple revisions to the package since then.  See the note on the Hackage page for the package, which says "Note: This package has [metadata revisions](https://hackage.haskell.org/package/diagrams-cairo-1.4.2.1/revisions/) in the cabal description newer than included in the tarball. To unpack the package including the revisions, use 'cabal get'."  When installing the package using `cabal` you should get the latest revision which includes the updated bound on `base`.

However, if the package is in fact not compiling under GHC 9.8 it may be due to a different issue.  How exactly are you trying to build it (*i.e.* what exact commands did you use) and what is the resulting error message?

**Comment by chansey97** [comment]
I don't know the metadata revision before. 

Thanks.

After `cabal update`, `diagrams-cairo` can build successfully on ghc-9.8.1 now.

The previous error is

```
Resolving dependencies...
Error: cabal.exe: Could not resolve dependencies:
[__0] trying: yampa-gloss-0.2.1 (user goal)
[__1] trying: yampa-gloss:+examples
[__2] trying: diagrams-cairo-1.4.2.1 (dependency of yampa-gloss +examples)
[__3] next goal: base (dependency of yampa-gloss)
[__3] rejecting: base-4.19.0.0/installed-efcd (conflict: diagrams-cairo =>
base>=4.2 && <4.19)
[__3] skipping: base-4.19.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=4.2 && <4.19' from
'diagrams-cairo')
[__3] rejecting: base-4.18.2.0, base-4.18.1.0, base-4.18.0.0, base-4.17.2.1,
base-4.17.2.0, base-4.17.1.0, base-4.17.0.0, base-4.16.4.0, base-4.16.3.0,
base-4.16.2.0, base-4.16.1.0, base-4.16.0.0, base-4.15.1.0, base-4.15.0.0,
base-4.14.3.0, base-4.14.2.0, base-4.14.1.0, base-4.14.0.0, base-4.13.0.0,
base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0, base-4.10.0.0,
base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
```
---

It seems that Hackage's updates has some delay for certain platforms (e.g. Windows). 

I remember that two days ago I updated cabal and it showed:

```
Package list of hackage.haskell.org is up to date.
The index-state is set to 2024-01-31T07:54:55Z.
```

It is clear that `2024-01-31` is not normal. 

So I tried it on Ubuntu, it shows `2024-02-12`, now problem.

Now Windows is OK too:

```
Package list of hackage.haskell.org has been updated.
The index-state is set to 2024-02-15T11:36:53Z.
```

Anyway, now everything is fine.
